#Experiment No.10
##Ayush Phale
##Entc, A-2
##PRN-25070123028
##Create a dataset and load dataset

In [1]:
#dataset creation
import pandas as pd
data={
    'Roll No.':['1','2','3','4','5'],
    'grender':['female','male','female','male','female'],
    'department':['entc','cse','it','mech','civil'],
    'cgpa':[8.2,9,7.8,9.3,7.7]
}
df=pd.DataFrame(data)
df.to_csv('student.csv',index=False)
df

  Roll No. grender department  cgpa
0        1  female       entc   8.2
1        2    male        cse   9.0
2        3  female         it   7.8
3        4    male       mech   9.3
4        5  female      civil   7.7

In [2]:
#adding a new column
df['age']=[17,18,19,18,19]
df

  Roll No. grender department  cgpa  age
0        1  female       entc   8.2   17
1        2    male        cse   9.0   18
2        3  female         it   7.8   19
3        4    male       mech   9.3   18
4        5  female      civil   7.7   19

In [3]:
df.shape

(5, 5)

In [4]:
df.size

25

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll No.    5 non-null      object
 1   grender     5 non-null      object
 2   department  5 non-null      object
 3   cgpa        5 non-null      float64
 4   age         5 non-null      int64
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [7]:
df.describe()

           cgpa       age
count  5.000000   5.00000
mean   8.400000  18.20000
std    0.717635   0.83666
min    7.700000  17.00000
25%    7.800000  18.00000
50%    8.200000  18.00000
75%    9.000000  19.00000
max    9.300000  19.00000

In [8]:
#access information of column department
df['department']

0     entc
1      cse
2       it
3     mech
4    civil
Name: department, dtype: object

In [9]:
#access information of PRN 103
df.loc[2]

Roll No.           3
grender       female
department        it
cgpa             7.8
age               19
Name: 2, dtype: object

In [10]:
#find out data types of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll No.    5 non-null      object
 1   grender     5 non-null      object
 2   department  5 non-null      object
 3   cgpa        5 non-null      float64
 4   age         5 non-null      int64
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [11]:
#perform mean, median ,mode operation
mean1=df['cgpa'].mean()
median1=df['cgpa'].median()
mode1=df['cgpa'].mode()
print(mean1)
print(median1)
print(mode1)

8.4
8.2
0    7.7
1    7.8
2    8.2
3    9.0
4    9.3
Name: cgpa, dtype: float64

In [12]:
#insert a new column grade
df['grade']=['B+','A','B','A+','B']
df

  Roll No. grender department  cgpa  age grade
0        1  female       entc   8.2   17    B+
1        2    male        cse   9.0   18     A
2        3  female         it   7.8   19     B
3        4    male       mech   9.3   18    A+
4        5  female      civil   7.7   19     B

In [13]:
#insert a new column grade
df['grade']=['B+','A','B','A+','B']
df

  Roll No. grender department  cgpa  age grade
0        1  female       entc   8.2   17    B+
1        2    male        cse   9.0   18     A
2        3  female         it   7.8   19     B
3        4    male       mech   9.3   18    A+
4        5  female      civil   7.7   19     B

In [14]:
#cgpa of topper
print('topper gpa:',df['cgpa'].max())

topper gpa: 9.3

In [15]:
#cpga of PRN 105
print('PRN 105 gpa:',df.loc[4,'cgpa'])

PRN 105 gpa: 7.7

In [16]:
#uploading a dataset to read
df=pd.read_csv('/content/Cars93.csv')
import numpy as np
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [17]:
df.size

930

In [19]:
df.shape

(93, 10)

In [20]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [21]:
display(df.head())

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [22]:
display(df.tail())

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0